name       : qt6-shadertools
version    : 6.3.0
release    : 5
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtshadertools-everywhere-src-6.3.0.tar.xz : 5498959b9d37c254bd126ab1320cf86aeb8a31b3ea7e51db666a8f9698afbd6c
license    : GPL-3.0-or-later
component  : desktop.qt
summary    : Qt Shader Tools module
description: |
    APIs and tools in this module provide the producer functionality for the shader pipeline that allows Qt Quick to operate on Vulkan in addition to OpenGL.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(spirv-cross-c-shared)
    - glslang-devel
rundeps    :
    - spirv-tools
    - devel :
        - qt6-base-devel
        - spirv-cross-devel
        - glslang-devel
setup      : |
    %patch -p1 < $pkgfiles/system-libs-instead.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -dm00755 $installdir/usr/bin
    ln -s /usr/lib64/qt6/bin/qsb $installdir/usr/bin/qsb
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
