name       : qt6-shadertools
version    : 6.2.2
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtshadertools-everywhere-src-6.2.2.tar.xz : f97505e72358c1fa2a2131c3a9a5b3497a2b9ea65b75a5beaf7f46c4b56a89e5
license    : GPL-3.0-or-later
component  : desktop.qt
summary    : Qt Shader Tools module
description: |
    APIs and tools in this module provide the producer functionality for the shader pipeline that allows Qt Quick to operate on Vulkan in addition to OpenGL.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(spirv-cross-c-shared)
    - glslang-devel
rundeps    :
    - spirv-tools
    - devel :
        - spirv-cross-devel
        - glslang-devel
setup      : |
    %patch -p1 < $pkgfiles/system-libs-instead.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -dm00755 $installdir/usr/bin
    ln -s /usr/lib64/qt6/bin/qsb $installdir/usr/bin/qsb
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
