name       : qt6-shadertools
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qtshadertools-everywhere-src-6.2.1.tar.xz : 2c8d38724181b31cd828a56e377775c2d461ee2ea0d6362ebec411c3b288067e
license    : GPL-3.0-or-later
component  : desktop.qt
summary    : Qt Shader Tools module
description: |
    APIs and tools in this module provide the producer functionality for the shader pipeline that allows Qt Quick to operate on Vulkan in addition to OpenGL.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(spirv-cross-c-shared)
    - glslang-devel
rundeps    :
    - spirv-tools
    - devel :
        - spirv-cross-devel
        - glslang-devel
setup      : |
    %patch -p1 < $pkgfiles/system-libs-instead.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -dm00755 $installdir/usr/bin
    ln -s /usr/lib64/qt6/bin/qsb $installdir/usr/bin/qsb
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
